// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB6BKtx7XrUam37z_bCkR9zhVCLaKh_g0',
    appId: '1:845084546928:web:1222f166e5ec6652f621b5',
    messagingSenderId: '845084546928',
    projectId: 'billingapp-94811',
    authDomain: 'billingapp-94811.firebaseapp.com',
    storageBucket: 'billingapp-94811.firebasestorage.app',
    measurementId: 'G-4VNHYC8KDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA174f-zxfoUS7pHAo3fYcKLsFO7LNrWLw',
    appId: '1:845084546928:android:82e865dcc99a9af7f621b5',
    messagingSenderId: '845084546928',
    projectId: 'billingapp-94811',
    storageBucket: 'billingapp-94811.firebasestorage.app',
  );
}
